[umpdc]
; NOTE: put this file in same dir as .dll & game.exe ofc
SDK_URL = http://127.0.0.1:21000
REDIRECT_HTTP = true

IL2CPP_STRING_NEW_LEN_PAT = E8 ? ? ? ? EB ? 31 C0 48 89 06 48 8B 47 ? 48 89 46 ? F2 0F 10 47
MAKE_INITIAL_URL_PAT = 55 41 56 56 57 53 48 81 EC 90 00 00 00 48 8D AC 24 ? ? ? ? 48 C7 45 ? ? ? ? ? 48 85 C9 74
SET_DITHER_PAT = E8 ? ? ? ? 84 C0 75 ? C7 43
APN_ALLOC_PAT = E8 ? ? ? ? 41 89 BF
SDK_PUBLIC_KEY_PAT = 48 8B 0D ? ? ? ? 4C 89 E2 E8 ? ? ? ? 48 89 C6 48 8B 0D ? ? ? ? E8 ? ? ? ? 48 89 C7 48 8B 0D

SDK_PUBLIC_KEY_XML = <RSAKeyValue><Exponent>AQAB</Exponent><Modulus>hEegnKISgDas5VTuRBUlixB+bvmPvXKa3kVO22UEZjPGMUFLmIl3DhH+dsZo7qJn/GfJCUkP1FA0MJ5Bj8PX8IatLJKIJ9dMCNdnAlkXTlMg86QQAhHZN83vP4swj5ILcrGNKl3YAZ49fvzo7nheuTt0/40f0HkHdNa1dUHECBs=</Modulus></RSAKeyValue>
SDK_PUBLIC_KEY_PEM = -----BEGIN PUBLIC KEY-----\nMIGfMA0GCSqGSIb3DQEBAQUAA4GNADCBiQKBgQCER6CcohKANqzlVO5EFSWLEH5u\n+Y+9cpreRU7bZQRmM8YxQUuYiXcOEf52xmjuomf8Z8kJSQ/UUDQwnkGPw9fwhq0s\nkogn10wI12cCWRdOUyDzpBACEdk3ze8/izCPkgtysY0qXdgBnj1+/OjueF65O3T/\njR/QeQd01rV1QcQIGwIDAQAB\n-----END PUBLIC KEY-----
